lua/oil/actions.lua

Using `vim.v.register`, we can respect the user's desire of copying to the unnamed (or unnamedplus) register or default one.
Check `:h v:register`
Thanks!

Respect 'clipboard' in copy_entry_path

---

lua/oil/adapters/ssh/sshfs.lua

Currently `oil-ssh` will raise an error if target machine do not use english locales:
```
...e/nvim/site/lazy/oil.nvim/lua/oil/adapters/ssh/sshfs.lua:25: Could
not parse '总用量 116'
stack traceback:
^I[C]: in function 'error'
^I...e/nvim/site/lazy/oil.nvim/lua/oil/adapters/ssh/sshfs.lua:25: in
function 'parse_ls_line'
^I...e/nvim/site/lazy/oil.nvim/lua/oil/adapters/ssh/sshfs.lua:137: in
function 'cb'
^I...m/site/lazy/oil.nvim/lua/oil/adapters/ssh/connection.lua:199: in
function '_handle_output'
^I...m/site/lazy/oil.nvim/lua/oil/adapters/ssh/connection.lua:102: in
function <...m/site/lazy/oil.nvim/lua/oil/adapters/ssh/connection.lu
a:99>
```

fix: oil-ssh assume target machine's locales

---

lua/oil/util.lua

This fixes an issue where a folder named `products.$id` gets evaluated to `products.<value of 'id' env var>`.

Escape dollar sign

---

lua/oil/init.lua

I was experiencing a bug where if I open a folder using `vim .`, the directory would still be opened with oil, even though I set default_file_explorer to false.
> I haven't tried recreating this bug with a minimal config yet. 
my config using packer:
```lua
use {
'stevearc/oil.nvim',
config = function()
require('oil').setup({
columns = {
"icon",
},
default_file_explorer = false,
})
end
}
```

Use default directory config when opening directories

---

lua/oil/init.lua

I'm not sure if this was intentional or not, but there is a specific highlight group for directories.
(This highlight group is used by other plugins e.g. netrw, nvim-tree)

Use standard directory highlight group

---

README.md
lua/oil/adapters/ssh/connection.lua
tests/url_spec.lua

This allows support of other *nix operating systems where bash is not universally present.
.... I routinely use both FreeBSD and Linux.  In FreeBSD, there is no `/bin/bash` -- if it's installed at all via ports, it's under `/usr/local/bin/bash`.
Switching this to `/bin/sh` seems to work fine with some rudimentary usage between various operating systems.   (On most Linuxes, this is bash anyway.  Or Dash.  Or something bash-like.  On the *BSDs, this is Bourne.  In any event, Oil appears to work across the board so far, and I'm pleased to be able to use it across platforms.

Use /bin/sh instead of bash.

---

lua/oil/actions.lua

Small updates for actions `open_cmd_line` and `open_cmdline_dir`.
- Escape special characters in the file path with `fnameescape()` .
- Invoke `nvim_feedkeys()` with `escape_ks=false` as suggested in `:h nvim_feedkeys()` (otherwise there may be problems when file path contains non-ANSCII character).

Escape metacharacters when loading file into cmdline

---

lua/oil/init.lua

closes #204 
There are a lot of problems with special characters and `:edit` on Windows. https://github.com/neovim/neovim/issues/3912 and https://github.com/vim/vim/issues/541
I think that with the current utilities, there is _literally_ no way to make `:edit` behave properly in all cases. As an example, on Windows:
`:edit fname$PATH.txt` will expand the `$PATH` variable, leading to a garbage filename
`:edit fname\$PATH.txt` will treat the `\` as a path separator, causing `fname` to be a directory and `$PATH.txt` the file within it.
I'm trying to work around this issue entirely by using `bufadd` to load the file path directly as a buffer, then using the `:buffer` command to switch to it. Preliminary results look good, but it needs more testing because I'm not at all confident that …

fix: previewing and editing files on windows

---

lua/oil/actions.lua

`<C-l>` is used to refresh the current directory, which is a good design. But there is a `CTRL-L-default` in neovim, which makes `<C-l>` a shortcut to execute `:nohlsearch`. I recommend respecting it to make oil like a real normal file.

feat: compatible with `CTRL-L-default`

---

lua/oil/init.lua

When saving sessions, the file that you source (i.e. `Session.vim`) executes `doautoall SessionLoadPost` which will execute the autocmd event `SessionLoadPost` on each buffer. So we don't need to manually loop over each buffer ourselves, the autocmd execution actually handles it for us. This causes an exponential growth in the number of times these calculations are made.
Also I found this while investigating #245 but sadly this doesn't fix the problem root there.
EDIT: ~I just pushed another performance improvement to check if `oil` is already loaded by checking the filetype. When restoring a session with `source` like the original issue #29 the filetype is not set to `oil`, but when loading views with `loadview` which also calls `SessionLoadPost` the oil buffers are already loaded and …

perf: only execute on current buffer since this event is called on each buffer

---

lua/oil/init.lua
lua/oil/util.lua

This PR adds the ability to set multiple hlgroups inside one column.
Related to https://github.com/stevearc/oil.nvim/issues/212
Before:
After:
To achieve the effect of the second screenshot, one has to setup oil as follows:
```lua
local permission_hlgroups = {
['-'] = 'NonText',
['r'] = 'DiagnosticSignWarn',
['w'] = 'DiagnosticSignError',
['x'] = 'DiagnosticSignOk',
}
oil.setup({
columns = {
{
'permissions',
highlight = function(permission_str)
local hls = {}
for i = 1, #permission_str do
local char = permission_str:sub(i, i)
table.insert(hls, { permission_hlgroups[char], i - 1, i })
end
return hls
end,
},
{ 'size', highlight = 'Special' },
{ 'mtime', highlight = 'Number' },
{
'icon',
default_file = icon_file,
directory = icon_dir,
add_padding = false,
},
},
win_options = {
number = …
```

feat: allow multiple hlgroups inside one column

---

doc/oil.txt
lua/oil/config.lua
lua/oil/view.lua

By default, the preview window is updated when the cursor is moved, but this behavior makes it heavy and sometimes stuck when opening large files.
So I added an option to make it behave like netrw's p key, which does not automatically synchronize.
I thought it would be good to allow users to choose which behavior they prefer.

feat: add 'update_on_cursor_moved' option to preview window

---

lua/oil/lsp_helpers.lua

Closes #247.
I think getting the relative path is unnecessary because the glob pattern will always match the full path, and it can mess up with some server filters, for example: tsserver uses `**/*.js` but the relative path omit the parent dir.

fix: willRename source path

---

README.md
doc/oil.txt
lua/oil/config.lua
lua/oil/lsp_helpers.lua

When moving or renaming files, my expectation was for all files referencing the changed file to be updated and written in the background. The current implementation seems to open all affected files in buffers, though each buffer needs to be manually written for the job to feel 'complete'.
This proposed change writes all affected buffers after `apply_workspace_edit` has executed. It then deletes all buffers that didn't exist prior to the move/rename action.

feat: auto-save files affected by will_rename_files

---

lua/oil/adapters/trash.lua
lua/oil/adapters/trash/windows.lua
lua/oil/config.lua
lua/oil/fs.lua
lua/oil/init.lua

This only adds support for `delete_to_trash` to the Windows trash adapter. I'm not sure about how the other adapters (freedesktop and mac) work, but at a glance I think they allow restoring files from trash, browsing files from trash, etc. Am I correct? I would like to help with the Windows trash adapter as much as I can, but I'm a bit lost.
Thanks for the amazing pluging, by the way :3.

feat(windows-trash): support for deleting to windows trash

---

lua/oil/adapters/trash/windows.lua
lua/oil/adapters/trash/windows/powershell-connection.lua
lua/oil/adapters/trash/windows/powershell-trash.lua

As mentioned in #243, trash support on windows is slow for some operations because it spawns a powershell process for every operation (sending 10 files to trash would spawn 10 powershell instances).
This PR starts two powershell intances (one for listing and one for deleting) and communicates with them over stdio (sending 10 files to trash now spawns only 1 powershell instance).
This improves the performance of trash related operations in windows after the first operation (because it's neccesary to start the powershell instance the first time). Maybe it could be preffered to start the powershell instances on startup instead (?).

perf(trash_windows): use a single powershell instance for operations

---

lua/oil/init.lua
lua/oil/util.lua
lua/oil/view.lua

Implements https://github.com/stevearc/oil.nvim/issues/236
Hi there! I'm a first-timer in this repo, so apologies in advance if I've missed any process for contributing
This setup has been working locally for me, so I decided to push up for some feedback, thanks in advance!
Also happy to add this to config, in case people would rather keep the existing behavior

feat: do not close preview when cd into dir

---

README.md
doc/oil.txt
lua/oil/adapters/ssh/connection.lua
lua/oil/config.lua
lua/oil/keymap_util.lua

Hi there,
First of all, thanks for Oil.nvim, awesome work!
Call me crazy, but one thing I really like, is to have control over how every window border looks within Neovim. Especially for consistency. I dislike it when one window has rounded borders and another one has double borders, etc.
Oil.nvim provides config options for almost every window, but not all of them. I forked this repo to allow configuring the border of the SSH window and the keymaps help window. If you like, you can merge it into master.
This gives us a total of 5 different borders we can configure, which raises the question if we might need a single configuration for all windows. Maybe a window config with overrides per window type, for those who want fine grained control? Something like this:
```lua
{
window_style = { …
```

Add border config for SSH and keymaps help window

---

lua/oil/init.lua

Fixes https://github.com/stevearc/oil.nvim/issues/295. Closing the preview window only when selecting an entry is not broad enough to handle when we change the buffer for some other reason (e.g. when doing `:edit`)

fix: close preview window when leaving oil buffer

---

README.md
doc/oil.txt
lua/oil/config.lua
lua/oil/lsp/helpers.lua
lua/oil/lsp/workspace.lua

I have a large repo in typescript where 1000ms is not enough time for LSP to resolve my rename file request. Therefore, I want to add a config that allows the user to alter the timeout, while keeping the default of 1000ms

feat: add ability to alter lsp file operation timeout

---

lua/oil/columns.lua
lua/oil/config.lua
lua/oil/view.lua

Does #306. Some screenshots of Oil after this change:
Before, the file `15` would come before `9`. Likewise, `v114.lua` would come before `v24.lua`
Happy to make this an optional feature!

Sort entries with natural sorting

---

lua/oil/columns.lua

There is a 'highlight' property in the docs for icon column but it doesn't work. So here is a fix.

fix: icon column highlight

---

lua/oil/lsp/helpers.lua
lua/oil/lsp/workspace.lua

fix(windows): convert posix paths before matching LSP watch globs

---

lua/oil/view.lua

Fixes an issue where attempting to delete hidden buffers when in a command window throws an error.
Ref: https://github.com/stevearc/oil.nvim/issues/390

Return from delete_hidden_buffers when win type is command

---

doc/oil.txt
lua/oil/actions.lua

Adds an action similar to `copy_entry_path`, but instead just copy the filename (without the path).

feat: add copy filename action

---

lua/oil/actions.lua

Right now both `actions.tcd` and `actions.cd` seem to do their job silently. That made me think the `~` key is broken(https://github.com/stevearc/oil.nvim/issues/397).
We can improve UX by providing these actions with info notifications, so the keypresses provide some visual response to the user.

feat: notify when changing the current directory

---

lua/oil/lsp/workspace.lua

Hi @stevearc, 
This is my very first PR to contribute to the most favorite plugin that I cannot live without. I raise a PR to fix the issue #410.
The root cause of the issue is that the plugin called `vim.has("nvim-0.11")` instead of `vim.fn.has("nvim-0.11")` in the file `lua/oil/lsp/workspace.lua`.
I would really appreciate if you can review my PR.
Thank you so much.

fix: cannot perform file/directory operations within LSP workspaces

---

lua/oil/adapters/files.lua
lua/oil/cache.lua

This will resolve #342, it improves the `is_modifiable` function for directories on unix systems by more accurately checking whether the user has write permission for the directory.
This PR changes the function so that it:
- Checks the groups that the nvim process owner is a part of, instead of only the group that nvim was launched with, this is done using the `id -G` command (gets all gid's of groups that the user is in) and checking if directory gid is in this list.
* note: the command output is cached upon first run if successful
* note: if the command fails it falls back to the previous behavior of only checking if the directory gid equal to the nvim process gid
- Accounts for weirder permission setups e.g. 170 and 117 (where the user is the owner of the directory) by still checking …

feat: improve is_modifiable checks for unix os's

---

lua/oil/init.lua
lua/oil/mutator/progress.lua

fix: set floating window win_options when buffer changes (#430)

---

lua/oil/mutator/preview.lua

feat: disable cursor in preview window

---

README.md
lua/oil/columns.lua
lua/oil/util.lua

This adds explicit support for [`mini.icons`](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-icons.md) for providing icons to oil. This generalizes the icon providing into a function that figures out which icon provider is available (preferring `mini.icons` over `nvim-web-devicons`) and returning a common icon providing interface.
`mini.icons` also has the ability to provide directory icons so this allows the icon provider to provide any type of icon and it's up to the provider to figure out how to handle what it can.
I tested it with each plugin individually as well as both and neither. It is working great! Let me know what you think of the implementation or if you have any recommendations to refactor this. I tried to match the code style and conventions in the codebase. …

feat: add support for `mini.icons`

---

lua/oil/util.lua

Some users may be using the full `mini.nvim` suite where `pcall(require, "mini.icons")` will return true but doesn't mean the user has actually set it up. This verifies that it is set up by checking for the existence of `_G.MiniIcons`.
This leaves the `pcall` just so (1) we load the plugin if it is lazy loaded by the user and (2) we get LSP completion/validation with that type as well.

fix: correctly check if `mini.icons` is actually setup

---

doc/api.md
doc/oil.txt
lua/oil/init.lua

Hi @stevearc, (big fan of your plugin here)
I had a small problem while integrating Oil with a tabline/statusline plugin (lualine.nvim). The problem was that sometimes I had multiple buffers open and Oil buffer wasn't always the currently hovered one. In such cases `get_current_dir` is not working as one would expect as it has a hardcoded reference to buffer `0`. My patch simply adds an optional parameter `bufnr` to said function to make it usable in such cases. This should not break the API in any way and I updated the documentation accordingly. If I screwed something up the PR is open for your edits :)
Cheers!

feat: allow bufnr optional parameter for get_current_dir function

---

lua/oil/adapters/ssh/connection.lua
lua/oil/adapters/ssh/sshfs.lua

This is a fix for a problem I had when using this plugin to SSH our servers at work.
We have group names containing spaces, which makes the line parsing break and raise an exception.
My solution was to work directly with the IDs of the users and groups.
Please let me know if there's a better or more appropriate solution, and I'll be happy to amend this PR.

fix: Handle users and groups with spaces correctly in SSH

---

lua/oil/adapters/ssh/sshfs.lua

The locale on the remote machine might result in an unexpected `ls` line, which crashes when parsing.
Therefore, forcing a known locale when executing `ls` for parsing might be better.

fix: Force standard C locale when getting `ls` input for parsing in SSH

---

lua/oil/view.lua

When `show_hidden` is set, we have no need to run `is_hidden_file`. This changes the order of the boolean logic so that the `show_hidden` value can short circuit the evaluation. This causes a significant performance increase when setting `show_hidden`.

perf(view): avoid running `is_hidden_file` when `show_hidden` is set

---

lua/oil/view.lua

Fixes an issue where `win_options` were being applied when opening a file in the jumplist at startup.
Ref: https://github.com/stevearc/oil.nvim/issues/398

Add check for filetype before setting win_options

---

doc/recipes.md

I have been using the `is_hidden_file` filter function for adding git integration relatively similar to the recipe that already exists. This makes a couple improvements, first it increases the performance of the `git ls-files` call by removing the need to iterate over a list of files each time, it also adds integration for showing tracked hidden files along with hiding ignored non-hidden files. I've been using this a bit and it has worked great even in huge repos. Let me know what you think!

doc(recipes): improve git integrated hidden files recipe

---

doc/oil.txt
lua/oil/adapters/trash/freedesktop.lua
scripts/generate.py

Keeping it pinned to `1.0`.
Fixes #489

doc: Update links to FreeDesktop's Trash spec

---

README.md
doc/oil.txt
lua/oil/config.lua

Allows to switch character case with ~ (tilde) in visual mode while preserving existing ~ :tcd functionality.
Related to [1].
[1]: https://github.com/stevearc/oil.nvim/issues/397 "bug: ~ not respected"

fix: only map ~ for normal mode

---

doc/oil.txt
lua/oil/config.lua
lua/oil/init.lua
lua/oil/util.lua

Add support to display the window title relative to the current working directory. See #382

Adding Customisability for floating window title.

---

doc/oil.txt
lua/oil/actions.lua

It looks like an unintened mistake to not pass the opts to the callback, because without it, the preview window cannot be a horizontal split.

fix: pass opts to actions.preview

---

lua/oil/actions.lua

Changed to add a trailing slash if the entry type is directory on yank_entry.
Closes #503

feat: add trailing slash on yank_entry

---

lua/oil/config.lua
lua/oil/init.lua
lua/oil/view.lua

This adds the ability to customize the window options for the preview window for files/directories. This takes a very basic approach, outside of just adding the `win_options` field to the lua type annotations it makes sure to set the `win_options` when creating the `previewwindow` windows. The other wrinkle it accounts for is to make sure to apply the `preview_win.win_options` after applying oil `win_options` if it's within a `previewwindow`. This makes sure it gets the necessary settings such as `conceal` and `concealcursor` while also applying the settings that the user wants for preview windows.
Let me know what you think of this approach!
Resolves #509

feat: add `win_options` to `preview_win`

---

lua/oil/util.lua

Changes the util file escape function to use the builtin `fnameescape` instead which fixes #529.

fix: improper file name escaping

---

lua/oil/init.lua
lua/oil/util.lua

Tentative fix for https://github.com/stevearc/oil.nvim/issues/524
closes https://github.com/stevearc/oil.nvim/issues/524

only use the previewwindow if requested by the user

---

lua/oil/view.lua

This PR fixes an issue with custom highlights on directories.
Currently, the custom highlights apply as requested, but remove the trailing '/', causing Oil to consider the directories as deleted and files with the same name as directories to be created.
Simple fix checks if the type is a directory and adds the '/' back

Fix custom directory highlights

---

README.md
doc/oil.txt
lua/oil/config.lua
lua/oil/view.lua

This PR enables you to determine the full directory path, enabling, for example, HL groups for Git.
Previously this was provided for `is_hidden_file` or `is_always_hidden` but not for `highlight_filename`.
Code changes are simple, since callers of `highlight_filename` always have bufnr anyway.

Add support for bufnr in custom highlights

---

README.md
doc/oil.txt
lua/oil/config.lua
lua/oil/layout.lua

This PR add support for setting `float.max_width` and `float.max_height` to a float between 0 and 1 (e.g. 0.4 for 40%)

feat: support floating window dimensions as float

---

lua/oil/init.lua

This PR restores the original window when opening file using the oil floating window. There is an implementation to restore the focused window but only works for the toggle action.

fix: restore previously focused window when opening file in multiple-split layout with an open preview window

---

README.md

Closes #539
Disabling lazy loading is necessary to set Oil as the default explorer when Neovim is initially opened.
Not 100% sure about the wording.

Add hint to disable lazy loading in lazy.nvim install

---

doc/oil.txt
lua/oil/actions.lua
lua/oil/util.lua

I have added the features from this issue: https://github.com/stevearc/oil.nvim/issues/522
By passing an additional option to the send_to_qflist action, one can now choose whether to only add files that matches the last search when search highlighting is enabled.  
In doing so I also found a bug with choosing whether to add or replace the entries in the quickfix list

Extend quickfix features

---

lua/oil/columns.lua
lua/oil/view.lua

This is primarily for user-defined custom columns, which may want access to the current path or similar information. The change is relatively simple since bufnr is necessarily always available when rendering columns, and will not break any consumers

Add support for bufnr in column rendering functions

---

lua/oil/adapters/trash/windows/powershell-connection.lua

Fixes #590
For some reason beyond my understanding, at least one of the following
things requires `noshellslash` to avoid the embeded powershell process to
send only `""` to the stdout (never calling the callback because
`"===DONE(True)==="` is never sent to stdout)
- `vim.fn.jobstart`
- `cmd.exe`
- `powershell.exe`
`shellslash` has been removed from Neovim nightly so I didn't put that much time into investigating why or how this is happening.

fix(trash-win): don't hang when `shellslash` is enabled

---

lua/oil/clipboard.lua

When environment variable `XDG_SESSION_DESKTOP` does not exist, copy files to clipboard will throw a nil value error. This PR adds nil checks for these environment variables.

fix: indexing nil when env vars does not exist

---

lua/oil/util.lua

Neovim version: **v0.12.0-dev-42+ge87d2ae383**
```
Failed to run 'config' for oil.nvim
... ~/.local/share/nvim/lazy/oil.nvim/lua/oil/util.lua:178: E565: Not allowed to change text or change window
* stacktrace:
- /oil.nvim/lua/oil/util.lua:178 _in_ **rename_buffer**
- /oil.nvim/lua/oil/init.lua:812 _in_ **maybe_hijack_directory_buffer**
- /oil.nvim/lua/oil/init.lua:1396 _in_ **setup**
- ~/ config/nvim/lua/tt/_plugins/oil.lua:18_in_ **setup**
- ~/. config/nvim/lua/tt/plugins.lua:575 _in_ **config**
```
This PR fixes an issue where oil.nvim throws an error (`E565: Not allowed to change text or change window`) when Neovim is started with a directory argument (e.g., `nvim .`). 
The error occurs because during initialization, the plugin attempts to delete buffers in a context where Neovim …

fix: prevent E565 error when opening directories with nvim .

---

lua/oil/lsp/workspace.lua

Fixes https://github.com/stevearc/oil.nvim/issues/630 that happened because of https://github.com/neovim/neovim/commit/322a6d305d088420b23071c227af07b7c1beb41a

fix: makes workaround conditional as it is no longer needed for 0.12

---

lua/oil/adapters/ssh/sshfs.lua

fixes https://github.com/stevearc/oil.nvim/issues/634, fallback to match the `iso8601` format

fix: add iso8601 format compatibility

---

lua/oil/columns.lua
lua/oil/view.lua

Changes the column ordering code when `view_options.natural_order` is enabled, so that it can support larger numbers.
I chose to handle numbers of up to 999 digits, because some cursory research seems to suggest to me that most filesystems cap at 255 bytes per segment, and 999 > 255, so it should be sufficient for all actual filenames.
Performance may have changed but I don't know if it will be better or worse.
I've slightly increased the complexity of the `string.format` format specifier, but the final strings will be shorter on average, and `string.format` no longer has to implicitly coerce `int` from a string into a number.
before:
after:

fix: support natural ordering for numbers with >12 digits

---

README.md

this replaced the links in the README.md file for the movement of the mini.nvim to a GtiHub organization

fix: replace 'echasnovski' in README.md with 'nvim-mini' for the move to organization
